Feature/fix text effect in tweet template
mahaelbasuony/twitter-clone pull request #35
Opened 2021-09-08 19:41 UTC by mahaelbasuony

<img width="1680" alt="Screenshot 2021-09-08 at 21 41 05" src="https://user-images.githubusercontent.com/30131427/132574592-6ac7925f-09a9-4236-ab38-7926c3f91c66.png">

2021-09-08 20:47 UTC, medhatdawoud requested changes
![Screenshot 2021-09-08 at 10 46 29 PM](https://user-images.githubusercontent.com/337888/132583156-5922080a-06d5-4a04-b517-60f1f65ac813.png)

this is not matching the design for the small numbers, it should work in both sizes for all numbers including single or double numbers and `+99` as well

2021-09-08 20:53 UTC, medhatdawoud commented
> ![Screenshot 2021-09-08 at 10 46 29 PM](https://user-images.githubusercontent.com/337888/132583156-5922080a-06d5-4a04-b517-60f1f65ac813.png)
> 
> this is not matching the design for the small numbers, it should work in both sizes for all numbers including single or double numbers and `+99` as well

ignore this , it is for another PR

2021-09-08 21:05 UTC, mahaelbasuony commented
> > ![Screenshot 2021-09-08 at 10 46 29 PM](https://user-images.githubusercontent.com/337888/132583156-5922080a-06d5-4a04-b517-60f1f65ac813.png)
> > this is not matching the design for the small numbers, it should work in both sizes for all numbers including single or double numbers and `+99` as well
> 
> ignore this , it is for another PR

okay ... can you check this PR for merge it 👍

2021-09-08 22:11 UTC, medhatdawoud commented on style.css
> +.tweet-template__icon::before{
why did you add `::before` here?

doesn't make sense, if should be there only with the `content: ' '` attribute as well to attach something to the element

2021-09-10 21:13 UTC, medhatdawoud approved these changes

2021-09-10 21:13 UTC, merged