create login form fix #38
mahaelbasuony/twitter-clone pull request #40
Opened 2021-09-13 06:15 UTC by mahaelbasuony

<img width="1680" alt="Screenshot 2021-09-13 at 08 14 59" src="https://user-images.githubusercontent.com/30131427/133032821-24f8958e-72e4-4596-9fd9-a8967c8fb604.png">

2021-09-13 19:21 UTC, medhatdawoud requested changes

2021-09-13 19:21 UTC, medhatdawoud commented on login.css
> +  --gray-800: #8394A1;
Nice making variables from the beginning 💪

2021-09-13 19:21 UTC, medhatdawoud commented on login.css
> +  padding: 0; */
why this is commented out?

2021-09-13 19:21 UTC, medhatdawoud commented on login.css
> +.userid__input, .password__input  {
better to give one generic form-control class and use it everywhere, imagine having to use more controls, will you add more selectors here?

2021-09-13 19:21 UTC, medhatdawoud commented on login.css
> +.userid__input:focus ~ label, .userid__input:not(:placeholder-shown) ~ label, .password__input:focus ~ label, .password__input:not(:placeholder-shown) ~ label{
Save here, please add one generic class and put all styles into it

2021-09-13 19:21 UTC, medhatdawoud commented on login.css
> +label {
Add a class name to label and use it here instead, don't use element names for styling

2021-09-13 19:21 UTC, medhatdawoud commented on login.css
> +  pointer-events:none;
could you explain to me here in a comment what does this property do ?

2021-09-13 19:21 UTC, medhatdawoud commented on login.css
> +}
Good one 😉

2021-09-13 19:21 UTC, medhatdawoud commented on login.html
> +        <input class="userid__input" type="text" placeholder=" ">
NO need to add `placeholder` attribute if you are not going to use it

2021-09-13 21:38 UTC, medhatdawoud requested changes
overall good job, one more thing to be fixed

2021-09-13 21:38 UTC, medhatdawoud commented on login.css
> +  padding-top: 10px;
padding should be symetric, right = left and top = bottom

2021-09-13 21:46 UTC, mahaelbasuony commented on login.css
> +  padding-top: 10px;
why?

2021-09-13 21:47 UTC, mahaelbasuony commented on login.css
> +  padding-top: 10px;
i tried it but didn't get same result

2021-09-15 22:21 UTC, medhatdawoud approved these changes
![](https://media0.giphy.com/media/eEXxfHQJ0dWOrctI55/200.gif?cid=5a38a5a28le0au2fujldwd6mf1gd4y64oe7j61z3u4gavrmt&rid=200.gif&ct=g)

2021-09-15 22:23 UTC, merged